name: Build
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: madhead/read-java-properties@latest
        id: all
        with:
          file: gradle.properties
          all: true
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
      
      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: gradle
          
      - name: Chmod Gradle Wrapper
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Make folder for artifacts
        run: mkdir artifacts
        
      - name: Move Forge Artifact
        run: mv forge/build/libs/${{ steps.all.outputs.mod_name }}-forge-${{ steps.all.outputs.mod_version }}+${{ steps.all.outputs.minecraft_version }}.jar artifacts/
        
      - name: Move Fabric Artifact
        run: mv fabric/build/libs/${{ steps.all.outputs.mod_name }}-fabric-${{ steps.all.outputs.mod_version }}+${{ steps.all.outputs.minecraft_version }}.jar artifacts/
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: artifacts/
